main: diduhless\stackcommands\StackCommands
name: StackCommands
description: A plugin that executes multiple commands with a single command
author: Didah (@diduhless)
website: https://github.com/Diduhless
version: 1.0.0
api: 3.0.0